include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_super_parameters: false
    deprecated_member_use: false
    use_build_context_synchronously: false
    library_private_types_in_public_api: false
    unused_local_variable: false
    unused_import: false

analyzer:
  errors:
    unused_import: info
    unused_local_variable: info
    deprecated_member_use: info
