name: resimanager
description: "Residence Management Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  fl_chart: ^0.70.2
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.6
  flutter_riverpod: ^2.5.1
  http: ^1.6.0
  pdf: ^3.11.0
  printing: ^5.13.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/residence_bg.png
    - assets/images/tranche_bg.png